name: PR test
on: [pull_request]

jobs:
  jennkins-shellcheck:
    runs-on: ubuntu-latest
    steps:
    - name: clone
      uses: actions/checkout@v3
    - uses: ./
      with:
        github_token: ${{ secrets.github_token }}
        # reporter: github-pr-review
        reporter: github-pr-check
        shellcheck_flags: "--exclude SC2086"
        reviewdog_flags: -tee
