name: Release drafter
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  draft_release:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    steps:
      - uses: release-drafter/release-drafter@v6
        id: release-drafter
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  publish_release:
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch'
    steps:
      - uses: release-drafter/release-drafter@v6
        id: release-drafter
        with:
          publish: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
